### ISSUE TITLE
Add widget as default on home screen

### ISSUE THREAD

**Issue by syefulislam** [isjeffcom/LiveFACE_LAUNCHER-OSP#1]
when i build and run this , I can't find any widget on my home screen. I want to add widget on home screen by default.
 
Not only clock, I wants to add weather or my widget at preload.
Thanks in advanced

**Comment by isjeffcom** [comment]
I am sorry to let you know, the team of this project was currently unavailable for fixing this issue. We are hoping that the participation of open sources community can maintain the project, otherwise we are not going to update unless the App is highly demanded.

**Comment by Modificator** [comment]
https://github.com/isjeffcom/LiveFACE_LAUNCHER-OSP/blob/Android-Studio/app/src/main/res/xml/default_workspace.xml
you can add your widget in there
by:
```xml
 <appwidget
        launcher:className="yourFullClassName"
        launcher:packageName="yourPkgName"
        launcher:screen="numOfWitchScreen"
        launcher:spanX="numOfWidgetWidth"
        launcher:spanY="numOfWidgetHeight"
        launcher:x="numOfWidgetLeft"
        launcher:y="numOfWidgetTop" />
```
