### ISSUE TITLE
Create rectangular  folder on Home Screen where i can put some icons in grid previw

### ISSUE THREAD

**Issue by syefulislam** [isjeffcom/LiveFACE_LAUNCHER-OSP#2]
I want to change folder icon and icon preview inside of folder. at new look Folder icon should rectangular view and add icon on folder shown in grid preview. Can anyone help regarding this issue.
Thanks

**Comment by Modificator** [comment]
https://github.com/isjeffcom/LiveFACE_LAUNCHER-OSP/blob/Android-Studio/app/src/main/res/xml/default_workspace.xml

```xml
<folder launcher:screen="numOfScreenIndex" launcher:x="numOfFolderLeft" launcher:y="numOfFolderLeftTop" launcher:title="folderTitleStr">
<!-- icon in folder -->
<favorite
            launcher:className="com.google.android.googlequicksearchbox.SearchActivity"
            launcher:packageName="com.google.android.googlequicksearchbox" />
</folder>
```
